// Regenerates src/data/art/portrait.ts from scripts/art/source.jpg.
// Runs generator.html in headless Chrome (set CHROME=/path/to/chrome to override).
import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const chrome = process.env.CHROME ?? "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome";

const dom = execFileSync(
  chrome,
  [
    "--headless=new",
    "--disable-gpu",
    "--allow-file-access-from-files",
    "--virtual-time-budget=20000",
    "--dump-dom",
    `file://${join(here, "generator.html")}`,
  ],
  { encoding: "utf8", maxBuffer: 64 * 1024 * 1024, stdio: ["ignore", "pipe", "ignore"] },
);

const match = dom.match(/<pre id="out">([\s\S]*?)<\/pre>/);
if (!match || !match[1].trim()) throw new Error("generator produced no output");
const json = match[1].replace(/&quot;/g, '"').replace(/&amp;/g, "&");
const data = JSON.parse(json);

const out = join(here, "../../src/data/art/portrait.ts");
writeFileSync(
  out,
  `// Generated by scripts/art/generate.mjs - do not edit by hand.\n` +
    `// Triangles are [x1, y1, x2, y2, x3, y3, paletteIndex].\n` +
    `const portrait: { w: number; h: number; palette: string[]; left: number[][]; right: number[][] } = ${JSON.stringify(data)};\n\n` +
    `export default portrait;\n`,
);
console.log(`wrote ${out}: ${data.left.length + data.right.length} triangles, ${data.palette.length} colours`);
